<?php
declare(strict_types=1);require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/artdon_pages_v710.php';$content=artdon_v710_content();$site=is_array($content['site']??null)?$content['site']:(function_exists('web_get_block')?(array)web_get_block('site'):[]);$footerBlock=is_array($content['footer']??null)?$content['footer']:(function_exists('web_get_block')?(array)web_get_block('footer'):[]);$siteUrl=artdon_v710_site_url($site);$company=trim((string)($site['company']??'Artdon Lighting Limited'))?:'Artdon Lighting Limited';$email=trim((string)($site['email']??'sales@artdon.cn'))?:'sales@artdon.cn';$title='Privacy Policy | Artdon Lighting';$desc='How Artdon Lighting handles information submitted through website inquiries, quotation requests and newsletter forms.';$canonical=$siteUrl.'/privacy.php';$schema=['@context'=>'https://schema.org','@graph'=>[['@type'=>'WebPage','url'=>$canonical,'name'=>$title,'description'=>$desc,'inLanguage'=>'en'],artdon_v710_breadcrumb_schema($siteUrl,[['name'=>'Home','url'=>''],['name'=>'Privacy Policy','url'=>'privacy.php']])]];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=artdon_v710_e($title)?></title><meta name="description" content="<?=artdon_v710_e($desc)?>"><meta name="robots" content="index,follow"><link rel="canonical" href="<?=artdon_v710_e($canonical)?>"><link rel="stylesheet" href="assets/css/artdon_home.css?v=6.12.16">
<link rel="stylesheet" href="assets/css/artdon_pages_v710.css?v=7.1.0"><script type="application/ld+json"><?=artdon_v710_json($schema)?></script></head><body><?php include __DIR__.'/partials/header.php';?><main class="artdon-page"><nav class="ap-breadcrumb"><a href="index.php">Home</a><span>/</span><strong>Privacy Policy</strong></nav><article class="ap-legal"><p class="ap-kicker">Website policy</p><h1>Privacy Policy</h1><p class="updated">Last updated: 23 June 2026</p>
<section><h2>Information you provide</h2><p>When you submit an inquiry, quotation request, technical-file request or newsletter form, we may receive your name, email address, company, country or region, product details and the message you provide.</p></section>
<section><h2>How the information is used</h2><p>We use submitted information to answer requests, prepare quotations, provide technical support, arrange samples, follow project requirements and maintain the business communication connected with your request.</p></section>
<section><h2>Website and server information</h2><p>Standard server logs may record technical information such as the requesting IP address, browser type, requested page and time of access. This information is used for website security, diagnostics and performance.</p></section>
<section><h2>Sharing and storage</h2><p>Information may be processed in the systems and service providers used to operate our website, email and customer follow-up. We do not publish inquiry information. Information is retained only as needed for business communication, legal obligations and system security.</p></section>
<section><h2>Your request</h2><p>You may ask us to correct or delete personal information connected with a website inquiry, subject to applicable business and legal retention requirements.</p></section>
<section><h2>Contact</h2><p>Privacy questions can be sent to <a href="mailto:<?=artdon_v710_e($email)?>"><?=artdon_v710_e($email)?></a>.</p></section>
</article></main><?php include __DIR__.'/partials/footer.php';?><script src="assets/js/artdon_home.js?v=6.12.14" defer></script></body></html>
