<?php
declare(strict_types=1);require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/artdon_pages_v710.php';$content=artdon_v710_content();$site=is_array($content['site']??null)?$content['site']:(function_exists('web_get_block')?(array)web_get_block('site'):[]);$footerBlock=is_array($content['footer']??null)?$content['footer']:(function_exists('web_get_block')?(array)web_get_block('footer'):[]);$siteUrl=artdon_v710_site_url($site);$title='Website Terms of Use | Artdon Lighting';$desc='Terms for using the Artdon Lighting website, product information and downloadable technical resources.';$canonical=$siteUrl.'/terms.php';$schema=['@context'=>'https://schema.org','@graph'=>[['@type'=>'WebPage','url'=>$canonical,'name'=>$title,'description'=>$desc,'inLanguage'=>'en'],artdon_v710_breadcrumb_schema($siteUrl,[['name'=>'Home','url'=>''],['name'=>'Terms of Use','url'=>'terms.php']])]];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=artdon_v710_e($title)?></title><meta name="description" content="<?=artdon_v710_e($desc)?>"><meta name="robots" content="index,follow"><link rel="canonical" href="<?=artdon_v710_e($canonical)?>"><link rel="stylesheet" href="assets/css/artdon_home.css?v=6.12.18">
<link rel="stylesheet" href="assets/css/artdon_pages_v710.css?v=7.1.0"><script type="application/ld+json"><?=artdon_v710_json($schema)?></script></head><body><?php include __DIR__.'/partials/header.php';?><main class="artdon-page"><nav class="ap-breadcrumb"><a href="index.php">Home</a><span>/</span><strong>Terms of Use</strong></nav><article class="ap-legal"><p class="ap-kicker">Website terms</p><h1>Terms of Use</h1><p class="updated">Last updated: 23 June 2026</p>
<section><h2>Website information</h2><p>This website provides general information about Artdon Lighting products, applications and services. Product data may be updated as designs, components or project configurations change.</p></section>
<section><h2>Technical files</h2><p>Datasheets, drawings, photometric files and BIM objects are provided for planning support. Confirm the final model, configuration and revision before using a file for procurement, installation or contractual documentation.</p></section>
<section><h2>Quotations and orders</h2><p>Website content is not a sales contract. Price, minimum order quantity, lead time, performance, certification, warranty and delivery terms are governed by the written quotation, proforma invoice or agreement issued for the specific order.</p></section>
<section><h2>Intellectual property</h2><p>Website text, graphics, product images, drawings and documents may not be republished as another company’s material without permission. Technical files may be used for legitimate project specification and coordination involving the relevant Artdon product.</p></section>
<section><h2>External links</h2><p>External websites and video platforms are operated by their respective providers. Artdon Lighting is not responsible for the availability or privacy practices of an external service.</p></section>
<section><h2>Questions</h2><p>Contact our team before relying on information that appears incomplete, inconsistent or unsuitable for a specific project condition.</p></section>
</article></main><?php include __DIR__.'/partials/footer.php';?><script src="assets/js/artdon_home.js?v=6.12.18" defer></script></body></html>
