<?php

declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/admin_auth.php';
require_once __DIR__ . '/_layout.php';
$dbError=null;$pdo=web_db($dbError);if(!$pdo){header('Location: login.php');exit;}web_migrate($pdo);$user=web_require_admin($pdo);web_admin_security_migrate($pdo);

function admin_logs_date_where(string $column,array &$where,array &$params,string $from,string $to):void{
    if($from!==''&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)){$where[]="$column>=?";$params[]=$from.' 00:00:00';}
    if($to!==''&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)){$where[]="$column<=?";$params[]=$to.' 23:59:59';}
}
function admin_logs_csv_cell(mixed $value): string{
    $text=(string)$value;
    return preg_match('/^[=+\-@\t\r]/u',$text) ? "'".$text : $text;
}
function admin_logs_csv(string $filename,array $headers,array $rows):never{
    header('Content-Type:text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');echo "\xEF\xBB\xBF";$out=fopen('php://output','wb');fputcsv($out,array_map('admin_logs_csv_cell',$headers));foreach($rows as $row)fputcsv($out,array_map('admin_logs_csv_cell',$row));fclose($out);exit;
}
function admin_logs_query_string(array $changes=[]):string{$data=array_merge($_GET,$changes);foreach($data as $k=>$v)if($v===''||$v===null)unset($data[$k]);return http_build_query($data,'','&',PHP_QUERY_RFC3986);}
function admin_logs_result_label(string $v):string{return ['success'=>'成功','error'=>'错误','denied'=>'已阻止','failure'=>'失败','locked'=>'锁定','blocked'=>'限流','ignored'=>'忽略','active'=>'在线','revoked'=>'已撤销','expired'=>'已过期'][$v]??$v;}

$tab=(string)($_GET['tab']??'actions');if(!in_array($tab,['actions','security','sync','sessions'],true))$tab='actions';
$q=trim((string)($_GET['q']??''));$userId=max(0,(int)($_GET['user_id']??0));$result=trim((string)($_GET['result']??''));$severity=trim((string)($_GET['severity']??''));$direction=trim((string)($_GET['direction']??''));$ip=trim((string)($_GET['ip']??''));$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$page=max(1,(int)($_GET['page']??1));$perPage=50;

if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        if(!web_verify_csrf($_POST['csrf']??null))throw new RuntimeException('页面已过期，请刷新后重试。');
        web_admin_require_permission($pdo,$user,'logs.cleanup');
        $source=(string)($_POST['source']??'actions');if(!in_array($source,['actions','security','sync','sessions','all'],true))throw new RuntimeException('日志清理范围不正确。');$days=max(30,min(3650,(int)($_POST['days']??180)));$cutoff=date('Y-m-d H:i:s',time()-$days*86400);$deleted=[];
        if($source==='actions'||$source==='all'){$stmt=$pdo->prepare('DELETE FROM web_audit_logs WHERE created_at<?');$stmt->execute([$cutoff]);$deleted['audit']=$stmt->rowCount();$stmt=$pdo->prepare('DELETE FROM web_admin_logs WHERE created_at<?');$stmt->execute([$cutoff]);$deleted['legacy']=$stmt->rowCount();}
        if($source==='security'||$source==='all'){$stmt=$pdo->prepare('DELETE FROM web_admin_login_attempts WHERE created_at<?');$stmt->execute([$cutoff]);$deleted['login']=$stmt->rowCount();}
        if($source==='sync'||$source==='all'){$stmt=$pdo->prepare('DELETE FROM web_sync_logs WHERE created_at<?');$stmt->execute([$cutoff]);$deleted['sync']=$stmt->rowCount();}
        if($source==='sessions'||$source==='all'){$stmt=$pdo->prepare('DELETE FROM web_admin_sessions WHERE (revoked_at IS NOT NULL OR expires_at<NOW()) AND created_at<?');$stmt->execute([$cutoff]);$deleted['sessions']=$stmt->rowCount();}
        web_audit_log($pdo,(int)$user['id'],'logs.cleanup','logs','log_source',$source,'清理历史日志',null,null,['retention_days'=>$days,'deleted'=>$deleted]);
        $_SESSION['admin_success']='历史日志已按 '.$days.' 天保留规则清理。';
    }catch(Throwable $e){$_SESSION['admin_error']=$e->getMessage();}
    header('Location: logs.php?tab='.rawurlencode($tab));exit;
}

$users=$pdo->query('SELECT id,username,display_name FROM web_admin_users ORDER BY display_name,username')->fetchAll();
$rows=[];$total=0;$stats=[];

if($tab==='actions'){
    $union="SELECT 'audit' source,id source_id,created_at,user_id,username_snapshot,action,module,target_type,target_key,result,severity,summary,detail_json,before_json,after_json,route,method,ip_address,user_agent,http_status,duration_ms FROM web_audit_logs
      UNION ALL
      SELECT 'legacy' source,id source_id,created_at,user_id,'' username_snapshot,action,target_type module,target_type,target_key,'success' result,'info' severity,'' summary,detail_json,NULL before_json,NULL after_json,'' route,'' method,ip_address,'' user_agent,NULL http_status,NULL duration_ms FROM web_admin_logs";
    $where=['1=1'];$params=[];
    if($q!==''){$where[]='(x.action LIKE ? OR x.module LIKE ? OR x.target_type LIKE ? OR x.target_key LIKE ? OR x.summary LIKE ? OR x.detail_json LIKE ? OR u.display_name LIKE ? OR u.username LIKE ?)';$n='%'.$q.'%';array_push($params,$n,$n,$n,$n,$n,$n,$n,$n);}
    if($userId>0){$where[]='x.user_id=?';$params[]=$userId;}if($result!==''){$where[]='x.result=?';$params[]=$result;}if($severity!==''){$where[]='x.severity=?';$params[]=$severity;}if($ip!==''){$where[]='x.ip_address LIKE ?';$params[]='%'.$ip.'%';}admin_logs_date_where('x.created_at',$where,$params,$from,$to);$whereSql=implode(' AND ',$where);
    $count=$pdo->prepare("SELECT COUNT(*) FROM ({$union}) x LEFT JOIN web_admin_users u ON u.id=x.user_id WHERE {$whereSql}");$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;
    $sql="SELECT x.*,COALESCE(u.display_name,u.username,x.username_snapshot,'系统') actor FROM ({$union}) x LEFT JOIN web_admin_users u ON u.id=x.user_id WHERE {$whereSql} ORDER BY x.created_at DESC,x.source_id DESC LIMIT {$perPage} OFFSET {$offset}";$stmt=$pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
    $stats=['24h'=>(int)$pdo->query("SELECT (SELECT COUNT(*) FROM web_audit_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR))+(SELECT COUNT(*) FROM web_admin_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR))")->fetchColumn(),'errors'=>(int)$pdo->query("SELECT COUNT(*) FROM web_audit_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND result IN ('error','denied')")->fetchColumn(),'users'=>(int)$pdo->query("SELECT COUNT(DISTINCT user_id) FROM web_audit_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND user_id IS NOT NULL")->fetchColumn(),'total'=>$total];
    if(!empty($_GET['export'])){web_admin_require_permission($pdo,$user,'logs.export');$sql="SELECT x.*,COALESCE(u.display_name,u.username,x.username_snapshot,'系统') actor FROM ({$union}) x LEFT JOIN web_admin_users u ON u.id=x.user_id WHERE {$whereSql} ORDER BY x.created_at DESC,x.source_id DESC LIMIT 10000";$stmt=$pdo->prepare($sql);$stmt->execute($params);$export=$stmt->fetchAll();web_audit_log($pdo,(int)$user['id'],'logs.export','logs','log_source','actions','导出操作日志',null,null,['rows'=>count($export),'filters'=>web_admin_sanitize($_GET)]);admin_logs_csv('artdon-actions-'.date('Ymd-His').'.csv',['时间','用户','操作','模块','对象','结果','级别','IP','页面','摘要'],array_map(fn($r)=>[$r['created_at'],$r['actor'],admin_action_label((string)$r['action']),$r['module'],trim($r['target_type'].' '.$r['target_key']),admin_logs_result_label((string)$r['result']),$r['severity'],$r['ip_address'],$r['route'],$r['summary']],$export));}
}elseif($tab==='security'){
    $where=['1=1'];$params=[];if($q!==''){$where[]='(a.username LIKE ? OR a.reason LIKE ? OR u.display_name LIKE ?)';$n='%'.$q.'%';array_push($params,$n,$n,$n);}if($userId>0){$where[]='a.user_id=?';$params[]=$userId;}if($result!==''){$where[]='a.result=?';$params[]=$result;}if($ip!==''){$where[]='a.ip_address LIKE ?';$params[]='%'.$ip.'%';}admin_logs_date_where('a.created_at',$where,$params,$from,$to);$whereSql=implode(' AND ',$where);$count=$pdo->prepare("SELECT COUNT(*) FROM web_admin_login_attempts a LEFT JOIN web_admin_users u ON u.id=a.user_id WHERE {$whereSql}");$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;$stmt=$pdo->prepare("SELECT a.*,COALESCE(u.display_name,u.username,a.username) actor FROM web_admin_login_attempts a LEFT JOIN web_admin_users u ON u.id=a.user_id WHERE {$whereSql} ORDER BY a.id DESC LIMIT {$perPage} OFFSET {$offset}");$stmt->execute($params);$rows=$stmt->fetchAll();
    $stats=['24h'=>(int)$pdo->query("SELECT COUNT(*) FROM web_admin_login_attempts WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)")->fetchColumn(),'success'=>(int)$pdo->query("SELECT COUNT(*) FROM web_admin_login_attempts WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND result='success'")->fetchColumn(),'failure'=>(int)$pdo->query("SELECT COUNT(*) FROM web_admin_login_attempts WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND result IN ('failure','locked','blocked')")->fetchColumn(),'total'=>$total];
    if(!empty($_GET['export'])){web_admin_require_permission($pdo,$user,'logs.export');$stmt=$pdo->prepare("SELECT a.*,COALESCE(u.display_name,u.username,a.username) actor FROM web_admin_login_attempts a LEFT JOIN web_admin_users u ON u.id=a.user_id WHERE {$whereSql} ORDER BY a.id DESC LIMIT 10000");$stmt->execute($params);$export=$stmt->fetchAll();web_audit_log($pdo,(int)$user['id'],'logs.export','logs','log_source','security','导出登录安全日志',null,null,['rows'=>count($export)]);admin_logs_csv('artdon-login-security-'.date('Ymd-His').'.csv',['时间','用户','登录账号','结果','原因','IP','设备'],array_map(fn($r)=>[$r['created_at'],$r['actor'],$r['username'],admin_logs_result_label((string)$r['result']),$r['reason'],$r['ip_address'],$r['user_agent']],$export));}
}elseif($tab==='sync'){
    $where=['1=1'];$params=[];if($q!==''){$where[]='(event_type LIKE ? OR message LIKE ? OR detail_json LIKE ?)';$n='%'.$q.'%';array_push($params,$n,$n,$n);}if($result!==''){$where[]='result=?';$params[]=$result;}if($direction!==''){$where[]='direction=?';$params[]=$direction;}admin_logs_date_where('created_at',$where,$params,$from,$to);$whereSql=implode(' AND ',$where);$count=$pdo->prepare("SELECT COUNT(*) FROM web_sync_logs WHERE {$whereSql}");$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;$stmt=$pdo->prepare("SELECT * FROM web_sync_logs WHERE {$whereSql} ORDER BY id DESC LIMIT {$perPage} OFFSET {$offset}");$stmt->execute($params);$rows=$stmt->fetchAll();$stats=['24h'=>(int)$pdo->query("SELECT COUNT(*) FROM web_sync_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)")->fetchColumn(),'success'=>(int)$pdo->query("SELECT COUNT(*) FROM web_sync_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND result='success'")->fetchColumn(),'errors'=>(int)$pdo->query("SELECT COUNT(*) FROM web_sync_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND result='error'")->fetchColumn(),'total'=>$total];
    if(!empty($_GET['export'])){web_admin_require_permission($pdo,$user,'logs.export');$stmt=$pdo->prepare("SELECT * FROM web_sync_logs WHERE {$whereSql} ORDER BY id DESC LIMIT 10000");$stmt->execute($params);$export=$stmt->fetchAll();web_audit_log($pdo,(int)$user['id'],'logs.export','logs','log_source','sync','导出同步日志',null,null,['rows'=>count($export)]);admin_logs_csv('artdon-sync-'.date('Ymd-His').'.csv',['时间','方向','事件','结果','HTTP','消息'],array_map(fn($r)=>[$r['created_at'],admin_status_label((string)$r['direction']),admin_event_label((string)$r['event_type']),admin_logs_result_label((string)$r['result']),$r['http_status'],$r['message']],$export));}
}else{
    $where=['1=1'];$params=[];if($q!==''){$where[]='(s.ip_address LIKE ? OR s.user_agent LIKE ? OR u.username LIKE ? OR u.display_name LIKE ?)';$n='%'.$q.'%';array_push($params,$n,$n,$n,$n);}if($userId>0){$where[]='s.user_id=?';$params[]=$userId;}if($result==='active')$where[]='s.revoked_at IS NULL AND s.expires_at>NOW()';elseif($result==='revoked')$where[]='s.revoked_at IS NOT NULL';elseif($result==='expired')$where[]='s.revoked_at IS NULL AND s.expires_at<=NOW()';if($ip!==''){$where[]='s.ip_address LIKE ?';$params[]='%'.$ip.'%';}admin_logs_date_where('s.created_at',$where,$params,$from,$to);$whereSql=implode(' AND ',$where);$count=$pdo->prepare("SELECT COUNT(*) FROM web_admin_sessions s LEFT JOIN web_admin_users u ON u.id=s.user_id WHERE {$whereSql}");$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;$stmt=$pdo->prepare("SELECT s.*,COALESCE(u.display_name,u.username,'未知账号') actor,u.username FROM web_admin_sessions s LEFT JOIN web_admin_users u ON u.id=s.user_id WHERE {$whereSql} ORDER BY s.last_seen_at DESC LIMIT {$perPage} OFFSET {$offset}");$stmt->execute($params);$rows=$stmt->fetchAll();$stats=['active'=>(int)$pdo->query("SELECT COUNT(*) FROM web_admin_sessions WHERE revoked_at IS NULL AND expires_at>NOW()")->fetchColumn(),'revoked'=>(int)$pdo->query("SELECT COUNT(*) FROM web_admin_sessions WHERE revoked_at IS NOT NULL")->fetchColumn(),'expired'=>(int)$pdo->query("SELECT COUNT(*) FROM web_admin_sessions WHERE revoked_at IS NULL AND expires_at<=NOW()")->fetchColumn(),'total'=>$total];
    if(!empty($_GET['export'])){web_admin_require_permission($pdo,$user,'logs.export');$stmt=$pdo->prepare("SELECT s.*,COALESCE(u.display_name,u.username,'未知账号') actor,u.username FROM web_admin_sessions s LEFT JOIN web_admin_users u ON u.id=s.user_id WHERE {$whereSql} ORDER BY s.last_seen_at DESC LIMIT 10000");$stmt->execute($params);$export=$stmt->fetchAll();web_audit_log($pdo,(int)$user['id'],'logs.export','logs','log_source','sessions','导出会话日志',null,null,['rows'=>count($export)]);admin_logs_csv('artdon-sessions-'.date('Ymd-His').'.csv',['创建时间','用户','IP','设备','最近活动','到期','撤销时间'],array_map(fn($r)=>[$r['created_at'],$r['actor'],$r['ip_address'],$r['user_agent'],$r['last_seen_at'],$r['expires_at'],$r['revoked_at']],$export));}
}
$pages=max(1,(int)ceil($total/$perPage));
admin_page_start('日志中心','logs',$user);admin_notice();
?>
<div class="security-page logs-page">
<nav class="logs-tabs"><a class="<?= $tab==='actions'?'is-active':'' ?>" href="?tab=actions">操作与变更</a><a class="<?= $tab==='security'?'is-active':'' ?>" href="?tab=security">登录安全</a><a class="<?= $tab==='sync'?'is-active':'' ?>" href="?tab=sync">双服务器同步</a><a class="<?= $tab==='sessions'?'is-active':'' ?>" href="?tab=sessions">登录会话</a></nav>
<section class="security-summary-grid logs-summary">
<?php if($tab==='actions'):?><article><span>筛选结果</span><strong><?= $stats['total'] ?></strong><small>操作与变更记录</small></article><article><span>最近 24 小时</span><strong><?= $stats['24h'] ?></strong><small>全部后台操作</small></article><article><span>错误/拦截</span><strong><?= $stats['errors'] ?></strong><small>需要检查</small></article><article><span>活跃账号</span><strong><?= $stats['users'] ?></strong><small>最近 24 小时</small></article>
<?php elseif($tab==='security'):?><article><span>筛选结果</span><strong><?= $stats['total'] ?></strong><small>登录安全记录</small></article><article><span>最近 24 小时</span><strong><?= $stats['24h'] ?></strong><small>登录尝试</small></article><article><span>登录成功</span><strong><?= $stats['success'] ?></strong><small>最近 24 小时</small></article><article><span>失败/锁定</span><strong><?= $stats['failure'] ?></strong><small>最近 24 小时</small></article>
<?php elseif($tab==='sync'):?><article><span>筛选结果</span><strong><?= $stats['total'] ?></strong><small>同步日志</small></article><article><span>最近 24 小时</span><strong><?= $stats['24h'] ?></strong><small>同步事件</small></article><article><span>同步成功</span><strong><?= $stats['success'] ?></strong><small>最近 24 小时</small></article><article><span>同步错误</span><strong><?= $stats['errors'] ?></strong><small>最近 24 小时</small></article>
<?php else:?><article><span>筛选结果</span><strong><?= $stats['total'] ?></strong><small>登录会话</small></article><article><span>当前在线</span><strong><?= $stats['active'] ?></strong><small>未撤销且未到期</small></article><article><span>已撤销</span><strong><?= $stats['revoked'] ?></strong><small>管理员或用户退出</small></article><article><span>已过期</span><strong><?= $stats['expired'] ?></strong><small>超过有效期</small></article><?php endif;?>
</section>
<section class="admin-card security-toolbar-card logs-toolbar"><form method="get" class="security-filterbar"><input type="hidden" name="tab" value="<?= web_e($tab) ?>"><input type="search" name="q" value="<?= web_e($q) ?>" placeholder="关键词、操作、对象或说明"><?php if($tab!=='sync'):?><select name="user_id"><option value="0">全部账号</option><?php foreach($users as $u):?><option value="<?= (int)$u['id'] ?>" <?= $userId===(int)$u['id']?'selected':'' ?>><?= web_e($u['display_name'].' · '.$u['username']) ?></option><?php endforeach;?></select><?php endif;?>
<?php if($tab==='actions'):?><select name="result"><option value="">全部结果</option><?php foreach(['success'=>'成功','error'=>'错误','denied'=>'已阻止'] as $k=>$v):?><option value="<?= $k ?>" <?= $result===$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select><select name="severity"><option value="">全部级别</option><?php foreach(['info'=>'信息','warning'=>'警告','error'=>'错误','critical'=>'严重'] as $k=>$v):?><option value="<?= $k ?>" <?= $severity===$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select>
<?php elseif($tab==='security'):?><select name="result"><option value="">全部结果</option><?php foreach(['success'=>'成功','failure'=>'失败','locked'=>'锁定','blocked'=>'限流'] as $k=>$v):?><option value="<?= $k ?>" <?= $result===$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select>
<?php elseif($tab==='sync'):?><select name="result"><option value="">全部结果</option><?php foreach(['success'=>'成功','error'=>'错误','ignored'=>'忽略'] as $k=>$v):?><option value="<?= $k ?>" <?= $result===$k?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select><select name="direction"><option value="">全部方向</option><option value="outbound" <?= $direction==='outbound'?'selected':'' ?>>香港→广州</option><option value="inbound" <?= $direction==='inbound'?'selected':'' ?>>广州→香港</option></select>
<?php else:?><select name="result"><option value="">全部状态</option><option value="active" <?= $result==='active'?'selected':'' ?>>在线</option><option value="revoked" <?= $result==='revoked'?'selected':'' ?>>已撤销</option><option value="expired" <?= $result==='expired'?'selected':'' ?>>已过期</option></select><?php endif;?>
<input type="text" name="ip" value="<?= web_e($ip) ?>" placeholder="IP"><input type="date" name="from" value="<?= web_e($from) ?>"><input type="date" name="to" value="<?= web_e($to) ?>"><button class="admin-button-secondary" type="submit">筛选</button><a class="admin-button-ghost" href="logs.php?tab=<?= web_e($tab) ?>">清空</a></form><div class="logs-toolbar-actions"><?php if(web_admin_user_can($user,'logs.export')):?><a class="admin-button-secondary" href="?<?= web_e(admin_logs_query_string(['export'=>1,'page'=>null])) ?>">导出 CSV</a><?php endif;?><?php if(web_admin_user_can($user,'logs.cleanup')):?><button class="admin-button-ghost" type="button" data-log-cleanup-open>清理日志</button><?php endif;?></div></section>
<section class="admin-card security-table-card logs-table-card"><div class="security-card-head"><div><h2><?= ['actions'=>'操作与变更','security'=>'登录安全','sync'=>'双服务器同步','sessions'=>'登录会话'][$tab] ?></h2><p>每页 50 条，支持筛选、详情和 CSV 导出。</p></div><span><?= $total ?> 条</span></div><?php if(!$rows):?><div class="empty">没有符合条件的日志。</div><?php else:?><div class="table-scroll"><table class="admin-table security-table logs-table"><thead><tr>
<?php if($tab==='actions'):?><th>时间</th><th>用户</th><th>操作</th><th>对象</th><th>结果</th><th>IP</th><th></th>
<?php elseif($tab==='security'):?><th>时间</th><th>用户/账号</th><th>结果</th><th>原因</th><th>IP</th><th>设备</th><th></th>
<?php elseif($tab==='sync'):?><th>时间</th><th>方向</th><th>事件</th><th>结果</th><th>HTTP</th><th>消息</th><th></th>
<?php else:?><th>用户</th><th>状态</th><th>IP</th><th>设备</th><th>最近活动</th><th>到期</th><th></th><?php endif;?></tr></thead><tbody>
<?php foreach($rows as $r):?>
<?php if($tab==='actions'):?><tr><td><?= web_e($r['created_at']) ?></td><td><?= web_e($r['actor']) ?></td><td><strong><?= web_e(admin_action_label((string)$r['action'])) ?></strong><small class="logs-code"><?= web_e($r['action']) ?></small></td><td><?= web_e(trim((string)$r['target_type'].' '.(string)$r['target_key'])) ?></td><td><span class="status-badge is-<?= in_array($r['result'],['error','denied'])?'danger':'success' ?>"><?= web_e(admin_logs_result_label((string)$r['result'])) ?></span></td><td><?= web_e($r['ip_address']) ?></td><td><a href="log_detail.php?source=<?= web_e($r['source']) ?>&id=<?= (int)$r['source_id'] ?>">详情</a></td></tr>
<?php elseif($tab==='security'):?><tr><td><?= web_e($r['created_at']) ?></td><td><strong><?= web_e($r['actor']) ?></strong><small class="logs-code"><?= web_e($r['username']) ?></small></td><td><span class="status-badge is-<?= $r['result']==='success'?'success':'danger' ?>"><?= web_e(admin_logs_result_label((string)$r['result'])) ?></span></td><td><?= web_e($r['reason']) ?></td><td><?= web_e($r['ip_address']) ?></td><td class="security-ua"><?= web_e($r['user_agent']) ?></td><td><a href="log_detail.php?source=login&id=<?= (int)$r['id'] ?>">详情</a></td></tr>
<?php elseif($tab==='sync'):?><tr><td><?= web_e($r['created_at']) ?></td><td><?= web_e(admin_status_label((string)$r['direction'])) ?></td><td><strong><?= web_e(admin_event_label((string)$r['event_type'])) ?></strong><small class="logs-code"><?= web_e($r['event_type']) ?></small></td><td><span class="status-badge is-<?= $r['result']==='error'?'danger':'success' ?>"><?= web_e(admin_logs_result_label((string)$r['result'])) ?></span></td><td><?= web_e($r['http_status']??'—') ?></td><td><?= web_e($r['message']) ?></td><td><a href="log_detail.php?source=sync&id=<?= (int)$r['id'] ?>">详情</a></td></tr>
<?php else:$state=!empty($r['revoked_at'])?'revoked':(strtotime((string)$r['expires_at'])<=time()?'expired':'active');?><tr><td><strong><?= web_e($r['actor']) ?></strong><small class="logs-code"><?= web_e($r['username']??'') ?></small></td><td><span class="status-badge is-<?= $state==='active'?'success':'muted' ?>"><?= web_e(admin_logs_result_label($state)) ?></span></td><td><?= web_e($r['ip_address']) ?></td><td class="security-ua"><?= web_e($r['user_agent']) ?></td><td><?= web_e($r['last_seen_at']) ?></td><td><?= web_e($r['expires_at']) ?></td><td><a href="log_detail.php?source=session&id=<?= (int)$r['id'] ?>">详情</a></td></tr><?php endif;?>
<?php endforeach;?></tbody></table></div><?php endif;?><?php if($pages>1):?><nav class="security-pagination"><?php for($i=max(1,$page-3);$i<=min($pages,$page+3);$i++):?><a class="<?= $i===$page?'is-active':'' ?>" href="?<?= web_e(admin_logs_query_string(['page'=>$i,'export'=>null])) ?>"><?= $i ?></a><?php endfor;?></nav><?php endif;?></section>
</div>
<?php if(web_admin_user_can($user,'logs.cleanup')):?><div class="security-modal" data-log-cleanup hidden><button class="security-modal-backdrop" type="button" data-log-cleanup-close></button><section><header><div><span class="security-eyebrow">Retention</span><h2>清理历史日志</h2></div><button type="button" data-log-cleanup-close>×</button></header><form method="post" data-confirm="日志清理后无法恢复，确定继续？"><input type="hidden" name="csrf" value="<?= web_e(web_csrf_token()) ?>"><div class="field"><label>清理范围</label><select name="source"><option value="<?= web_e($tab) ?>">当前模块</option><option value="all">全部日志</option></select></div><div class="field"><label>保留最近</label><select name="days"><option value="90">90 天</option><option value="180" selected>180 天</option><option value="365">365 天</option><option value="730">730 天</option></select></div><p>只删除超过保留期的历史记录；在线会话不会被删除。</p><footer><button class="admin-button-secondary" type="button" data-log-cleanup-close>取消</button><button class="admin-button is-danger" type="submit">确认清理</button></footer></form></section></div><?php endif;?>
<?php admin_page_end(); ?>
