<?php

declare(strict_types=1);

function web_default_content(): array
{
    return [
        'site' => [
            'company' => 'Artdon Lighting Limited',
            'site_url' => 'http://43.132.210.162',
            'header_logo' => 'assets/img/logo-artdon.png',
            'footer_logo' => 'assets/img/logo-artdon-footer.png',
            'favicon' => 'assets/img/favicon-artdon.png',
            'tagline' => 'Architectural Lighting for Commercial Spaces',
            'contact_name' => 'Sukie',
            'email' => 'sales@artdon.cn',
            'telephone' => '+86-760-22211886',
            'mobile' => '+86-13925332972 / +86-13751710245',
            'whatsapp' => '8613925332972',
            'location' => 'No. 15 Zhihe 3rd Street, Yumin Dongsheng, Xiaolan Town, Zhongshan City, Guangdong, China (Post Code: 528414)',
            'facebook' => '',
            'instagram' => '',
            'linkedin' => '',
            'pinterest' => '',
            'youtube' => 'videos.php',
            'x' => '',
            'tiktok' => '',
            'header_quote_label' => 'Get a Quote',
            'header_quote_url' => 'index.php#contact',
            'quote_modal_kicker' => 'Project support',
            'quote_modal_title' => 'Project inquiry',
            'quote_modal_subtitle_template' => 'Inquiry about: {project}',
            'quote_modal_subtitle_default' => 'Send us your product or project requirement.',
            'quote_modal_side_text' => "Share your project requirement.\nOur team will route it to the right sales and technical owner.",
            'quote_modal_notice_title' => 'CRM + dispatch linked',
            'quote_modal_notice_text' => 'Your inquiry is saved and assigned automatically. Fastest reply within 1 hour.',
            'quote_modal_trust_1' => 'Connected to CRM and dispatch system.',
            'quote_modal_trust_2' => 'Fastest response within 1 hour.',
            'quote_modal_trust_3' => 'Product, sample or project details are tracked clearly.',
            'quote_modal_name_label' => 'Name *',
            'quote_modal_email_label' => 'Email *',
            'quote_modal_company_label' => 'Company',
            'quote_modal_country_label' => 'Country',
            'quote_modal_requirement_label' => 'Project requirement',
            'quote_modal_requirement_placeholder' => 'Tell us quantity, project type, beam angle, CCT or other requirements.',
            'quote_modal_cancel_label' => 'Cancel',
            'quote_modal_submit_label' => 'Submit inquiry',
            'nav_schema_version' => 49,
            'nav' => [
                ['label'=>'Home','href'=>'index.php','items'=>[]],
                ['label'=>'Products','href'=>'products.php','items'=>[
                    ['label'=>'All Products','href'=>'products.php'],
                    ['label'=>'Downlights','href'=>'products.php?type=downlight'],
                    ['label'=>'Track Lights','href'=>'products.php?type=track'],
                    ['label'=>'Magnetic Systems','href'=>'products.php?type=magnetic'],
                    ['label'=>'Linear Lighting','href'=>'products.php?type=linear'],
                    ['label'=>'Outdoor Lighting','href'=>'products.php?type=outdoor'],
                ]],
                ['label'=>'Solutions','href'=>'project.php','items'=>[
                    ['label'=>'Retail Lighting','href'=>'project.php?type=retail'],
                    ['label'=>'Hospitality Lighting','href'=>'project.php?type=hospitality'],
                    ['label'=>'Museum & Gallery','href'=>'project.php?type=museum'],
                    ['label'=>'Office Lighting','href'=>'project.php?type=office'],
                    ['label'=>'Residential Lighting','href'=>'project.php?type=residential'],
                    ['label'=>'Outdoor & Landscape','href'=>'project.php?type=exterior'],
                ]],
                ['label'=>'Projects','href'=>'project.php','items'=>[
                    ['label'=>'All Projects','href'=>'project.php'],
                    ['label'=>'Retail','href'=>'project.php?type=retail'],
                    ['label'=>'Hospitality','href'=>'project.php?type=hospitality'],
                    ['label'=>'Office','href'=>'project.php?type=office'],
                    ['label'=>'Residential','href'=>'project.php?type=residential'],
                    ['label'=>'Museum & Gallery','href'=>'project.php?type=museum'],
                    ['label'=>'Commercial','href'=>'project.php?type=commercial'],
                ]],
                ['label'=>'About Us','href'=>'index.php#about','items'=>[
                    ['label'=>'Why Artdon','href'=>'index.php#about'],
                    ['label'=>'Manufacturing','href'=>'index.php#why-choose-artdon'],
                    ['label'=>'Quality & Testing','href'=>'index.php#why-choose-artdon'],
                    ['label'=>'OEM / ODM','href'=>'index.php#why-choose-artdon'],
                ]],
                ['label'=>'Resources','href'=>'downloads.php','items'=>[
                    ['label'=>'Catalogue','href'=>'downloads.php?type=catalogues'],
                    ['label'=>'Blog & Insights','href'=>'index.php#knowledge'],
                    ['label'=>'FAQ','href'=>'contact.php#faq'],
                    ['label'=>'Downloads','href'=>'downloads.php'],
                    ['label'=>'Video','href'=>'videos.php'],
                ]],
                ['label'=>'Contact','href'=>'contact.php','items'=>[]],
            ],
        ],
        'seo' => [
            'title' => 'Artdon Lighting | Architectural Lighting for Commercial Spaces',
            'description' => 'Commercial architectural lighting products, project applications, technical files and custom lighting support from Artdon Lighting Limited.',
            'og_image' => 'assets/img/hero/hero-track-systems.webp',
            'robots' => 'index,follow,max-image-preview:large',
        ],
        'homepage_layout' => [
            'sections' => [
                ['key'=>'hero','label'=>'首页轮播','active'=>1,'order'=>10],
                ['key'=>'why','label'=>'关于我们','active'=>1,'order'=>20],
                ['key'=>'reasons','label'=>'合作优势','active'=>1,'order'=>25],
                ['key'=>'products','label'=>'产品系列','active'=>1,'order'=>30],
                ['key'=>'featured_system','label'=>'重点系统','active'=>1,'order'=>40],
                ['key'=>'projects','label'=>'项目案例','active'=>1,'order'=>50],
                ['key'=>'downloads','label'=>'下载中心','active'=>1,'order'=>60],
                ['key'=>'insights','label'=>'知识文章','active'=>1,'order'=>70],
                ['key'=>'inquiry','label'=>'询盘表单','active'=>1,'order'=>80],
            ],
        ],
        'hero' => [
            'quote_button' => 'Get a quote',
            'slides' => [
                [
                    'active'=>1,
                    'eyebrow'=>'48V Magnetic System',
                    'title'=>'Flexible light for architectural interiors.',
                    'desc'=>'Linear modules, accent spotlights and low-glare optics on one compact track system.',
                    'image'=>'assets/img/hero/hero-track-systems.webp',
                    'video'=>'assets/video/hero-track-systems.mp4',
                    'alt'=>'Black architectural magnetic track lighting system with multiple lighting modules',
                    'link'=>'products.php?type=magnetic',
                    'cta'=>'Explore the system',
                    'quote_product'=>'48V Magnetic System'
                ],
                [
                    'active'=>1,
                    'eyebrow'=>'Outdoor Lighting',
                    'title'=>'Precise luminaires for exterior projects.',
                    'desc'=>'Compact projectors, façade lighting and IP-rated solutions for landscape and architecture.',
                    'image'=>'assets/img/hero/hero-outdoor-projector.webp',
                    'video'=>'',
                    'alt'=>'Black outdoor architectural projector with warm optical reflector',
                    'link'=>'products.php?type=outdoor',
                    'cta'=>'View outdoor products',
                    'quote_product'=>'Outdoor Architectural Projector'
                ],
                [
                    'active'=>1,
                    'eyebrow'=>'Technical Support',
                    'title'=>'Product files ready for specification.',
                    'desc'=>'Datasheets, IES/LDT, BIM/Revit, drawings, manuals and certificates organised by product.',
                    'image'=>'assets/img/hero/hero-technical-downloads.webp',
                    'video'=>'',
                    'alt'=>'Lighting product technical files, photometric data and BIM resources',
                    'link'=>'downloads.php',
                    'cta'=>'Open download center',
                    'quote_product'=>'Technical Files / Product Specification Support'
                ],
            ],
        ],
        'why' => [
            'eyebrow'=>'Why Artdon',
            'title'=>'Your Trusted Lighting Manufacturing Partner',
            'intro'=>'With extensive experience in LED commercial lighting, we combine product development, manufacturing, quality verification and responsive service to support demanding projects.',
            'cards'=>[
                ['active'=>1,'icon'=>'factory','title'=>'In-House Manufacturing','text'=>'Integrated support from prototyping and machining to finishing, assembly, inspection and packaging.'],
                ['active'=>1,'icon'=>'quality','title'=>'Quality Verification','text'=>'Thermal, integrating sphere, IES and EMC verification help keep product performance clear and consistent.'],
                ['active'=>1,'icon'=>'global','title'=>'Global Project Support','text'=>'Responsive communication, technical files and export support for designers, distributors and contractors.'],
                ['active'=>1,'icon'=>'idea','title'=>'R&D Innovation','text'=>'Custom optics, structures, finishes and dimensions developed around real commercial lighting applications.'],
                ['active'=>1,'icon'=>'speed','title'=>'Responsive Development','text'=>'Clear sample iterations and project milestones help move custom lighting ideas efficiently toward production.'],
                ['active'=>1,'icon'=>'shield','title'=>'OEM / ODM Expertise','text'=>'From concept and sample development to private-label production, documentation and long-term product support.'],
            ],
        ],

        'reasons' => [
            'eyebrow'=>'Why Choose Artdon',
            'title'=>'6 Reasons to Partner With Us',
            'intro'=>'',
            'cards'=>[
                ['active'=>1,'icon'=>'experience','badge'=>'2007','title'=>'Since 2007','text'=>'Artdon has been dedicated to architectural and commercial lighting with stable manufacturing and project support experience.','button_label'=>'Learn More About Us','button_url'=>'contact.php'],
                ['active'=>1,'icon'=>'custom','badge'=>'','title'=>'OEM & ODM Capability','text'=>'From concept to product, we provide custom designs, private labels and project-based solutions to meet your unique needs.','button_label'=>'Start Your Custom Project','button_url'=>'contact.php'],
                ['active'=>1,'icon'=>'factory','badge'=>'','title'=>'In-house Manufacturing','text'=>'CNC machining, assembly, testing and quality control are completed in-house to support stable production.','button_label'=>'Visit Our Factory','button_url'=>'contact.php'],
                ['active'=>1,'icon'=>'delivery','badge'=>'','title'=>'Fast Response & Delivery','text'=>'Quick response to inquiries and flexible production scheduling support samples, projects and repeat orders.','button_label'=>'Contact Us Now','button_url'=>'contact.php'],
                ['active'=>1,'icon'=>'quality','badge'=>'','title'=>'Quality Assurance','text'=>'A structured quality-control process and reliable components support long service life and consistent performance.','button_label'=>'Quality Assurance','button_url'=>'downloads.php'],
                ['active'=>1,'icon'=>'global','badge'=>'','title'=>'Global Export Experience','text'=>'Professional documentation, logistics coordination and project support help customers serve international markets.','button_label'=>'View Export Support','button_url'=>'project.php'],
            ],
        ],
        'products' => [
            'eyebrow'=>'Products',
            'title'=>'Product families',
            'view_all_label'=>'View all products',
            'view_all_url'=>'products.php',
            'tabs'=>[
                ['key'=>'all','label'=>'All'],
                ['key'=>'downlight','label'=>'Downlight'],
                ['key'=>'track','label'=>'Track light'],
                ['key'=>'magnetic','label'=>'Magnetic'],
                ['key'=>'linear','label'=>'Linear'],
                ['key'=>'outdoor','label'=>'Outdoor'],
                ['key'=>'optics','label'=>'Optics'],
            ],
            'items'=>[
                ['active'=>1,'featured'=>0,'title'=>'Recessed downlight','type'=>'Downlight','image'=>'assets/img/product-micro.svg','text'=>'Compact recessed luminaire for clean ceilings and precise general lighting.','url'=>'products.php?type=downlight','categories'=>'downlight'],
                ['active'=>1,'featured'=>0,'title'=>'Adjustable downlight','type'=>'Downlight','image'=>'assets/img/product-axis.svg','text'=>'Directional recessed light for displays, artwork and feature areas.','url'=>'products.php?type=downlight','categories'=>'downlight'],
                ['active'=>1,'featured'=>0,'title'=>'Trimless downlight','type'=>'Downlight','image'=>'assets/img/product-micro.svg','text'=>'Minimal trimless integration for refined architectural interiors.','url'=>'products.php?type=downlight','categories'=>'downlight'],
                ['active'=>1,'featured'=>1,'title'=>'48V magnetic system','type'=>'Systems','image'=>'assets/img/products/track-system-full.webp','text'=>'One slim track for linear, spotlight and grille modules.','url'=>'products.php?type=magnetic','categories'=>'magnetic'],
                ['active'=>1,'featured'=>1,'title'=>'Track spotlight','type'=>'Accent','image'=>'assets/img/products/track-spot-module.webp','text'=>'Adjustable beam control for retail, museum and gallery lighting.','url'=>'products.php?type=track','categories'=>'track magnetic'],
                ['active'=>1,'featured'=>1,'title'=>'Linear module','type'=>'Linear','image'=>'assets/img/products/track-linear-module.webp','text'=>'Continuous light for shelves, corridors and architectural details.','url'=>'products.php?type=linear','categories'=>'linear magnetic'],
                ['active'=>1,'featured'=>1,'title'=>'Grille optic','type'=>'Low glare','image'=>'assets/img/products/track-grille-module.webp','text'=>'Multi-cell optics for comfortable and controlled commercial lighting.','url'=>'products.php?type=optics','categories'=>'track magnetic optics'],
                ['active'=>1,'featured'=>1,'title'=>'Outdoor projector','type'=>'Outdoor','image'=>'assets/img/products/outdoor-projector-full.webp','text'=>'Compact IP-rated projector for façade and landscape applications.','url'=>'products.php?type=outdoor','categories'=>'outdoor'],
                ['active'=>1,'featured'=>1,'title'=>'Optical detail','type'=>'Engineering','image'=>'assets/img/products/outdoor-lens-detail.webp','text'=>'Reflector and lens design for precise beam distribution.','url'=>'products.php?type=optics','categories'=>'optics outdoor'],
                ['active'=>1,'featured'=>0,'title'=>'Surface linear light','type'=>'Linear','image'=>'assets/img/product-linea.svg','text'=>'A clean linear form for circulation, workspaces and continuous illumination.','url'=>'products.php?type=linear','categories'=>'linear'],
                ['active'=>1,'featured'=>0,'title'=>'Track wall washer','type'=>'Track light','image'=>'assets/img/products/track-system-full.webp','text'=>'Wide and even vertical illumination for walls, displays and galleries.','url'=>'products.php?type=track','categories'=>'track'],
                ['active'=>1,'featured'=>0,'title'=>'Bollard light','type'=>'Outdoor','image'=>'assets/img/product-outdoor.svg','text'=>'Durable low-level lighting for paths, landscape and exterior circulation.','url'=>'products.php?type=outdoor','categories'=>'outdoor'],
            ],
        ],
        'featured_system' => [
            'eyebrow'=>'Featured system',
            'title'=>'One track. Multiple lighting tools.',
            'text'=>'Combine general light, accent light and low-glare optical modules on a compact 48V magnetic track.',
            'image'=>'assets/img/products/track-system-full.webp',
            'alt'=>'48V magnetic track lighting system with linear and spotlight modules',
            'url'=>'products.php?type=magnetic',
            'link_label'=>'View magnetic system',
            'features'=>[
                ['title'=>'Linear','text'=>'Continuous light for circulation and shelving.'],
                ['title'=>'Accent','text'=>'Adjustable spotlights for displays and artwork.'],
                ['title'=>'Low glare','text'=>'Grille and dark-light optics for visual comfort.'],
            ],
        ],
        'projects' => [
            'eyebrow'=>'Projects',
            'title'=>'Featured Lighting Projects',
            'intro'=>'See how Artdon luminaires shape retail and hospitality interiors through precise accent lighting, visual comfort and carefully layered illumination.',
            'view_all_label'=>'View all projects',
            'view_all_url'=>'project.php',
            'items'=>[
                ['active'=>1,'type'=>'Retail','year'=>'2026','title'=>'Fashion Boutique Lighting','place'=>'Commercial interior','desc'=>'Track spotlights and concealed linear light create clear visual zones, comfortable contrast and focused merchandise presentation.','image'=>'assets/img/projects/featured-retail.webp','url'=>'project.php?type=retail'],
                ['active'=>1,'type'=>'Hospitality','year'=>'2026','title'=>'Hotel Lobby Lighting','place'=>'Hospitality interior','desc'=>'Warm ambient layers, decorative accents and controlled downlighting shape a welcoming arrival experience.','image'=>'assets/img/projects/featured-hospitality.webp','url'=>'project.php?type=hospitality'],
                ['active'=>1,'type'=>'Museum','year'=>'2025','title'=>'Gallery Accent Lighting','place'=>'Museum and gallery interior','desc'=>'Flexible accent luminaires and low-glare optics support precise artwork illumination while maintaining a calm visual environment.','image'=>'assets/img/projects/featured-museum.webp','url'=>'project.php?type=museum'],
                ['active'=>1,'type'=>'Office','year'=>'2025','title'=>'Executive Reception Lighting','place'=>'Corporate interior','desc'=>'Layered downlighting and warm architectural details create a professional reception space with balanced brightness and visual comfort.','image'=>'assets/img/projects/featured-office.webp','url'=>'project.php?type=office'],
            ],
        ],
        'downloads' => [
            'eyebrow'=>'Technical support',
            'title'=>'Find product files.',
            'intro'=>'Search by model or browse catalogues, photometric files, BIM/Revit resources, drawings, manuals and certificates.',
            'search_placeholder'=>'Product name or model',
            'search_button'=>'Search',
            'open_label'=>'Open',
            'items'=>[
                ['active'=>1,'title'=>'Catalogues','desc'=>'Company profile, product catalogues and collection brochures','type'=>'catalogues'],
                ['active'=>1,'title'=>'Photometric data','desc'=>'IES, LDT, DIALux and Relux files for lighting design','type'=>'photometric'],
                ['active'=>1,'title'=>'2D / 3D / BIM','desc'=>'DWG, DXF, STEP, 3DS, Revit and BIM resources','type'=>'bim'],
                ['active'=>1,'title'=>'Manuals & certificates','desc'=>'Installation guides, datasheets, CE, RoHS and test reports','type'=>'manuals'],
            ],
        ],
        'insights' => [
            'eyebrow'=>'Resources',
            'title'=>'Insights & Knowledge',
            'intro'=>'Expert articles on LED lighting technology, application guides and commercial project specification.',
            'view_all_label'=>'View all resources',
            'view_all_url'=>'downloads.php',
            'items'=>[
                ['active'=>1,'tag'=>'Application','title'=>'Energy-efficient LED lighting solutions for shopping malls','text'=>'Explore how modern track lights, downlights and control strategies can reduce energy use while improving merchandising and visual comfort.','image'=>'assets/img/projects/featured-retail.webp','alt'=>'Luxury retail interior illuminated with track spotlights and architectural lighting','date'=>'Mar 15, 2026','read'=>'8 min read','url'=>'contact.php?topic=shopping-mall-lighting','fit'=>'cover'],
                ['active'=>1,'tag'=>'Purchasing','title'=>"A buyer's guide to high-performance LED downlights",'text'=>'A practical overview of optical control, CRI, glare, drivers, finishes, dimensions and installation details for commercial projects.','image'=>'assets/img/product-micro.svg','alt'=>'Minimal recessed architectural downlight with controlled beam','date'=>'Feb 20, 2026','read'=>'10 min read','url'=>'contact.php?topic=downlight-selection','fit'=>'contain'],
                ['active'=>1,'tag'=>'Technical','title'=>'Understanding CRI and colour quality in commercial lighting','text'=>'Learn how CRI, R9, colour consistency and beam control affect retail, museum, hospitality and gallery applications.','image'=>'assets/img/projects/featured-museum.webp','alt'=>'Commercial gallery and retail interior with controlled accent lighting','date'=>'Jan 10, 2026','read'=>'6 min read','url'=>'contact.php?topic=cri-colour-quality','fit'=>'cover'],
            ],
        ],
        'inquiry' => [
            'eyebrow'=>'Project inquiry',
            'title'=>'Tell us what your project needs.',
            'intro'=>'Send a product model, drawing, quantity, beam angle, CCT/CRI requirement or project deadline. Our team will respond with the relevant product and technical information.',
            'button'=>'Send inquiry',
            'success_message'=>'Thank you. Your inquiry has been received.',
            'quote_eyebrow'=>'Quotation request',
            'quote_title'=>'Get a quote.',
            'quote_intro'=>'Send your contact details and the selected product will be included automatically.',
            'quote_button'=>'Send quote request',
            'quote_note'=>'Our sales team will reply by email.',
            'name_label'=>'Name',
            'name_placeholder'=>'Your name',
            'email_label'=>'Work email',
            'email_placeholder'=>'name@company.com',
            'company_label'=>'Company',
            'company_placeholder'=>'Company name',
            'country_label'=>'Country / Region',
            'country_placeholder'=>'Country',
            'support_label'=>'What do you need?',
            'message_label'=>'Product / project requirements',
            'message_placeholder'=>'Product model, quantity, beam angle, CCT/CRI, drawings, project type or deadline.',
            'consent_text'=>'I agree that Artdon Lighting may use this information to respond to my inquiry.',
            'response_note'=>'Usually answered within one working day.',
            'quote_name_label'=>'Customer name',
            'quote_email_label'=>'Email',
            'quote_product_label'=>'Selected product',
            'support_options'=>[
                ['value'=>'product','label'=>'Product information'],
                ['value'=>'quotation','label'=>'Quotation'],
                ['value'=>'technical-files','label'=>'IES / LDT / BIM files'],
                ['value'=>'sample','label'=>'Sample request'],
                ['value'=>'custom-project','label'=>'Custom project support'],
            ],
        ],
        'footer' => [
            'newsletter_title'=>'Stay inspired',
            'newsletter_text'=>'Subscribe for product updates, project references and lighting insights.',
            'newsletter_button'=>'Subscribe',
            'newsletter_placeholder'=>'Enter your email address',
            'projects_support_heading'=>'Projects / Support',
            'contact_heading'=>'Contact',
            'contact_person_label'=>'Contact',
            'email_label'=>'Email',
            'telephone_label'=>'Tel',
            'mobile_label'=>'Mobile / WhatsApp',
            'copyright'=>'© 2026 Artdon Lighting Limited',
            'legal'=>[
                ['label'=>'Privacy Policy','href'=>'contact.php#privacy'],
                ['label'=>'Cookie Policy','href'=>'contact.php#cookies'],
                ['label'=>'Terms & Conditions','href'=>'contact.php#terms'],
                ['label'=>'Download Center','href'=>'downloads.php'],
            ],
        ],
    ];
}
